export const data = [
  {
    id: 1,
    user: "Punit",
    Organization: "Rainbow Mumbai Hospitals",
    Email: "Punit+care.provider+6@unify.digital",
    userDesc: "@Punit",
    status: "Active",
    Roles: ["Doctor HOD"],
    Updated: "Mar 14, 2024 12:34 PM",
  },
  {
    id: 2,
    user: "Dipanhsu",
    Organization: "Rainbow Mumbai Hospitals",
    userDesc: "@Dipanhsu",
    Email: "Dipanhsu+care.provider+6@unify.digital",
    status: "Pending",
    Roles: "Nurse",
    Updated: "Mar 14, 2024 12:34 PM",
  },
  {
    id: 3,
    user: "Mohan",
    Organization: "--",
    userDesc: "@mohan",
    Email: "mohan+care.provider+6@unify.digital",
    status: "Active",
    Roles: "Admin",
    Updated: "Mar 14, 2024 12:34 PM",
  },
  {
    id: 4,
    user: "Dora Sai Teja",
    Organization: "Rainbow Mumbai Hospitals",
    userDesc: "@Dora Sai Tejal",
    Email: "DoraSaiTeja+care.provider+6@unify.digital",
    status: "Active",
    Roles: "Doctor",
    Updated: "Mar 14, 2024 12:34 PM",
  },
];

export const UserFrom = {
  UserBasicInfo: [
    {
      type: "text",
      label: "Organization",
      id: "organization",
      placeholder: "Select Organization",
    },
    {
      type: "text",
      label: "Email",
      id: "Email",
      placeholder: "Email",
    },
    {
      type: "dropdown",
      label: "Phone Number",
      id: "PNumber",
      placeholder: "Enter your Number",
    },
    {
      type: "text",
      label: "First Name",
      id: "FirstName",
      placeholder: "First Name",
    },
    {
      type: "text",
      label: "Last Name",
      id: "LastName",
      placeholder: "Last Name",
    },
    {
      type: "text",
      label: "Gender",
      id: "gender",
      placeholder: "Gender",
      options: ["Male", "Female"],
    },
    {
      type: "dropdown",
      label: "User Profile",
      id: "Profile",
      placeholder: "User Profile",
      options: ["Admin", "Doctor", "Nurse", "Staff"],
    },
  ],
};
